FROM alpine:latest
WORKDIR /config-src
COPY nitter.conf sessions.jsonl ./
CMD ["sh", "-c", "cp /config-src/nitter.conf /config-src/sessions.jsonl /config/ && chmod 0444 /config/nitter.conf /config/sessions.jsonl"]
